### ISSUE TITLE
CURL as alternative?

### ISSUE THREAD

**Issue by MauTG** [blockchain/api-v1-client-python#127]
-- nevermind --

please close this issue.

**Comment by Oelofse1991** [comment]
Dont feel alone mine also dont open?

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 27, 2020 at 20:23, Mau<notifications@github.com> wrote:   


Hi,

Because I'm not getting the output as I normally would get with cURL, I'm kindly asking how to do a simple blockexplorer-query using cURL.

I've tried several times, but I'm still getting rate-limited AKA the key isn't accepted when using cURL.

curl -v -H @{'api_code' = 'MY_API_CODE'} "https://blockchain.info/rawaddr/3BMEXoMmdnueY3LL9NqBnqRN3hCViSUq7m"

curl -s "https://blockchain.info/rawaddr/3BMEXoMmdnueY3LL9NqBnqRN3hCViSUq7m?api_code=MY_API_CODE"

curl -s "https://blockchain.info/rawaddr/3BMEXoMmdnueY3LL9NqBnqRN3hCViSUq7m&api_code=MY_API_CODE"

curl -s "https://blockchain.info/rawaddr/3BMEXoMmdnueY3LL9NqBnqRN3hCViSUq7m?api_key=MY_API_CODE"

curl -s "https://blockchain.info/rawaddr/3BMEXoMmdnueY3LL9NqBnqRN3hCViSUq7m&api_key=MY_API_CODE"

Could someone please help me out?
