### ISSUE TITLE
From address

### ISSUE THREAD

**Issue by perldev** [blockchain/api-v1-client-python#42]
it will be very useful if it is possible to use many addresses in from_adress  param in send transaction api call

**Comment by alecalve** [comment]
If you leave it as `None`, it will use several addresses if none can fulfil the requested amount.

AFAIK, there's no way to specify several sources addresses. If this is a feature you'd like, I recommend you opening an issue on the [service-my-wallet-v3 repo](https://github.com/blockchain/service-my-wallet-v3) since that's where they are implemented.
