### ISSUE TITLE
Maybe the fields returned from the API could be a little better documented?

### ISSUE THREAD

**Issue by mattdornfeld** [blockchain/api-v1-client-python#71]
Looking at the fields available on the Input class
```

n : int
value : int
address : str
tx_index : int
type : int
script : str
script_sig : str
sequence : int
```

I'm not really sure what those all mean.

**Comment by MatteoRomiti** [comment]
I agree on adding more details and as soon as I can, I'll try to contribute. 
One question more, though: why do we get an array of `block` objects from `get_block_height`? I'd expect to get one single `block` object.

**Comment by RayXY** [comment]
Those naming reflects how we name those in the actual HTTP API so for consistency purpose it is better to keep them the same.

@mattdornfeld Firstly you can get some basics of input from resources like this: https://bitcoin.org/en/developer-reference#txin And the section you posted here are in the 'Previous Output' section.

There a few noticeable addition/rename
n: index for the previous output in its transaction
value: the amount of satoshi in this output
address: the bitcoin address the output is targeting
tx_index: instead of tx_hash, we provide our internal transaction index which can be used to query transaction in our /tx endpoint
type: 0 for standard output

**Comment by RayXY** [comment]
@MatteoRomiti when a block fork happens there is a chance two (or more) blocks may be at same height thus this return a list. In normal situation there should be only one item in the list.
